export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE",
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  DATABASE_ERROR = "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
